# Generated by Django 5.0.3 on 2024-03-30 17:31

import class_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, unique=True, validators=[class_app.validators.validate_subject_format])),
                ('professor', models.CharField(max_length=255, validators=[class_app.validators.validate_professor_name])),
                ('students', models.ManyToManyField(related_name='classes', to='student_app.student')),
            ],
        ),
    ]
